name: algodroid_pro
description: "AlgoDroid Pro Premium Trading Application Framework"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.1.1
  cupertino_icons: ^1.0.6

flutter:
  uses-material-design: true
