name: AlgoDroid Pro Android Cloud Build

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.19.0'
          channel: 'stable'

      - name: Generate Clean Project Structure
        run: |
          mkdir -p temp_backup
          cp main.dart temp_backup/main.dart
          cp pubspec.yaml temp_backup/pubspec.yaml
          rm -rf *
          flutter create . --org com.algodroid.pro --project-name algodroid_pro --overwrite
          rm -f lib/main.dart
          cp temp_backup/main.dart lib/main.dart
          cp temp_backup/pubspec.yaml pubspec.yaml

      - name: Load Dependencies
        run: flutter pub get

      - name: Compile Master Release APK
        run: flutter build apk --debug --no-pub

      - name: Upload Clean Master APK
        uses: actions/upload-artifact@v4
        with:
          name: AlgoDroid-Pro-Installation-File
          path: build/app/outputs/flutter-apk/app-debug.apk
