name: AlgoDroid Pro Android Cloud Build

on:
  workflow_dispatch: # मोबाईलवरून मॅन्युअली रन करण्यासाठी बटण देईल

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository Code
        uses: actions/checkout@v3

      - name: Set up Java Development Kit (JDK)
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Set up Flutter Environment
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.19.0'
          channel: 'stable'

      - name: Install App Dependencies
        run: flutter pub get

      - name: Compile and Build Release APK
        run: flutter build apk --debug --no-pub # पहिल्यांदा टेस्ट करण्यासाठी फास्ट डीबग बिल्ड

      - name: Upload Finished APK To Download Section
        uses: actions/upload-artifact@v3
        with:
          name: AlgoDroid-Pro-Installation-File
          path: build/app/outputs/flutter-apk/app-debug.apk
